services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - GUNICORN_CMD_ARGS=--timeout 120
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      permissions:
        condition: service_completed_successfully
      db:
        condition: service_started
      cache:
        condition: service_started
    networks:
        default:
        internal:
        frp-network:

  # TODO: CTFd 4.0 Migrate to named volumes. Users will likely need to manually migrate existing files
  permissions:
    image: alpine:3.23
    user: root
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    command: chown -R 1001:1001 /var/uploads /var/log/CTFd

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - ctfd
    networks:
      default:
      frp-network:

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiMmIwY2QzZmM5N2JmZjM4ZmVmMTkzOWMxZThmZDIzOWUiLCJ0IjoiZTgwNTQ5YzktZmI4MS00OTFmLWIxMDgtYTE4MDZhYTM3ZDU2IiwicyI6Ill6SmhNV1poWmpZdFpqWm1aaTAwTm1KbExXRmlNamt0TlRFMk1HRm1aakJrTkdReiJ9
    depends_on:
      - nginx

  frps:
    image: fatedier/frps:v0.52.3
    restart: always
    command: ["-c", "/etc/frp/frps.ini"]
    ports:
      - "7000:7000"
      - "10000-10100:10000-10100"
    volumes:
      - ./conf/frp/frps.ini:/etc/frp/frps.ini
    networks:
      - frp-network

  frpc:
    image: fatedier/frpc:v0.52.3
    restart: always
    command: ["-c", "/etc/frp/frpc.ini"]
    volumes:
      - ./conf/frp/frpc.ini:/etc/frp/frpc.ini
    depends_on:
      - frps
    networks:
      - frp-network

networks:
    default:
    internal:
        internal: true
    frp-network:
        name: ctfd_frp-containers
        external: true
